#:schema node_modules/wrangler/config-schema.json
name = "curious-kitchen-server"
main = "index.ts"
compatibility_date = "2024-10-11"
workers_dev = true

[[durable_objects.bindings]]
name = "TinyBaseDurableObjects"
class_name = "TinyBaseDurableObject"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TinyBaseDurableObject"]
